services:
  - type: web
    name: timetrip
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    # Python version is specified in runtime.txt file
    envVars:
      - key: PORT
        value: 10000

